import { createExtensionClient } from '@forgeax/workbench-host/extension'

export type WorkbenchHostClient = ReturnType<typeof createExtensionClient>

let client: WorkbenchHostClient | undefined
let injected: WorkbenchHostClient | undefined
let runtimeAnnounced = false
let runtimeBindingListenerInstalled = false

/**
 * The runtime id is intentionally generated by the extension's local host, so
 * the Studio parent cannot safely guess it from the plugin id. Announce the
 * public catalog binding from the iframe's own origin; the parent still binds
 * the resulting nonce handshake to this exact iframe and origin.
 */
function announceRuntimeBinding(): void {
  if (runtimeAnnounced || typeof window === 'undefined' || window.parent === window) return
  runtimeAnnounced = true
  void (async () => {
    try {
      const gameId = new URLSearchParams(window.location.search).get('slug')
      if (!gameId || !/^[a-z0-9][a-z0-9-]{0,40}$/.test(gameId)) return
      const response = await fetch(
        `/__workbench__/v1/catalog?gameId=${encodeURIComponent(gameId)}`,
      )
      if (!response.ok) return
      const catalog = await response.json() as Array<{
        extensionId?: unknown
        runtimeId?: unknown
      }>
      const runtime = catalog.find((entry) => (
        entry?.extensionId === '@forgeax-extension/wb-game-video'
        && typeof entry.runtimeId === 'string'
      ))
      if (!runtime || typeof runtime.runtimeId !== 'string') return
      const parentOrigin = document.referrer ? new URL(document.referrer).origin : '*'
      window.parent.postMessage({
        type: 'workbench:runtime:ready',
        extensionId: '@forgeax-extension/wb-game-video',
        gameId,
        runtimeId: runtime.runtimeId,
      }, parentOrigin)
    } catch {
      // A standalone page has no Studio parent to bind; GameBootstrap surfaces
      // the normal host-required state in that mode.
    }
  })()
}

/**
 * A keep-alive iframe may outlive a Studio HMR remount. In that case the new
 * parent has no controller yet, while this module has already announced its
 * runtime once. Let the parent explicitly request a fresh announcement.
 */
function installRuntimeBindingListener(): void {
  if (runtimeBindingListenerInstalled || typeof window === 'undefined') return
  runtimeBindingListenerInstalled = true
  window.addEventListener('message', (event) => {
    if (
      event.source === window.parent
      && event.data?.type === 'workbench:runtime:request'
    ) {
      runtimeAnnounced = false
      announceRuntimeBinding()
    }
  })
}

/**
 * The workbench client every consumer shares.
 *
 * In an iframe there is no client until one is built here, and building it
 * starts the parent handshake. An in-process host has no parent to shake hands
 * with, so it injects an already-connected client instead.
 */
export function getWorkbenchHost(): WorkbenchHostClient {
  if (injected) return injected
  installRuntimeBindingListener()
  announceRuntimeBinding()
  return client ??= createExtensionClient()
}

/** Installs the host-supplied client used by in-process (non-iframe) mounts. */
export function setWorkbenchHost(next: WorkbenchHostClient): void {
  injected = next
}

export function clearWorkbenchHost(): void {
  injected = undefined
}

export class ExtensionResponseError extends Error {
  constructor(readonly status: number, message: string) {
    super(message)
    this.name = 'ExtensionResponseError'
  }
}

function isJsonContentType(value: string | null): boolean {
  const mediaType = value?.split(';', 1)[0]?.trim().toLowerCase()
  return mediaType === 'application/json' || Boolean(mediaType?.endsWith('+json'))
}

/** Parses only successful, explicitly JSON extension-router responses. */
export async function readExtensionJson(response: Response): Promise<unknown> {
  if (!response.ok) {
    throw new ExtensionResponseError(response.status, `Extension request failed (${response.status})`)
  }
  if (!isJsonContentType(response.headers.get('content-type'))) {
    throw new ExtensionResponseError(response.status, 'Extension returned a non-JSON response')
  }
  let body: unknown
  try {
    body = await response.json()
  } catch {
    throw new ExtensionResponseError(response.status, 'Extension returned malformed JSON')
  }
  return body
}
