// MeshyProvider — real submit/poll client for the Meshy.ai public OpenAPI.
//
// Decoupling (ADR-0001): like HunyuanWorkflowProvider, this talks to the remote
// API and returns a pure ProviderResult with downloaded bytes. It knows nothing
// about cache, asset-store, or manifests. Auth is plain `Authorization: Bearer
// <key>` (key prefix `msy_`/`msy-`); no signing.
//
// Differences from Hunyuan workflow (see hunyuan3d-lab docs/API_REFERENCE.md):
//   - text-to-3D uses v2 (`/openapi/v2/text-to-3d`), image/multi use v1.
//   - submit returns the task id in `result` (v2) or `id` (v1).
//   - status is UPPER-CASE: PENDING/IN_PROGRESS/SUCCEEDED/FAILED/CANCELED.
//   - outputs come back as `model_urls` (dict), `texture_urls[]`, `thumbnail_url`.
//   - text is two-stage: `preview` (white mesh) then `refine` (adds texture),
//     where refine takes a `preview_task_id` from a prior preview task.

import { clampTargetPolycount, type ProviderResult, type ProviderResultFile } from '../../shared/catalog';
import type { FileFormat, FileRole, GenerationMode } from '../../shared/manifest';
import { MESHY_ACTIONS, MESHY_ACTION_BASE } from '../../shared/meshy-actions';
import type { MeshyEnv } from '../env';
import { audit } from '../audit';
import { RateGuard } from '../rate-guard';

const PATH_TEXT = '/openapi/v2/text-to-3d';
const PATH_IMAGE = '/openapi/v1/image-to-3d';
const PATH_MULTI = '/openapi/v1/multi-image-to-3d';
// Rig / animation are async submit→poll tasks (ADR-0006 / PLAN §2). Unlike the
// generation modes, rig/anim results carry their OWN url keys (see §2.3), so
// they reuse the poll loop but extract different fields.
const PATH_RIGGING = '/openapi/v1/rigging';
const PATH_ANIMATION = '/openapi/v1/animations';
const PATH_BALANCE = '/openapi/v1/balance';

const SUCCESS = 'SUCCEEDED';
const FAILURE = new Set(['FAILED', 'CANCELED']);

export type MeshyMode = 'text' | 'image' | 'views' | 'refine';

export interface MeshyGenerateInput {
  mode: MeshyMode;
  prompt?: string;
  imageUrl?: string;
  imageUrls?: string[];
  previewTaskId?: string;
  texturePrompt?: string;
  enablePbr?: boolean;
  shouldTexture?: boolean;
  targetPolycount?: number;
  aiModel?: string;
  params?: Record<string, string | number | boolean>;
}

// ── Rig / animation I/O (ADR-0006) ──────────────────────────────────────────

export interface MeshyRigInput {
  // Meshy mesh task id — the fast path when the source was just generated by
  // Meshy and is not expired. Either this OR modelUrl is required.
  inputTaskId?: string;
  // Public model URL (e.g. a COS transfer URL). Preferred per PLAN §8-Q5.
  modelUrl?: string;
  heightMeters?: number;
}

export interface MeshyAnimateInput {
  // Meshy's OWN rig task id (NOT a local FBX). Meshy animation only accepts this.
  rigTaskId: string;
  actionId: number;
}

// One free animation bundled in a /rigging result (no extra credits). The
// `armature_glb` variant exists upstream but is not downloaded here (YAGNI; the
// playable glb + the fbx transport cover preview + .zip export — see §8-Q6).
export interface MeshyBasicAnimation {
  category: 'walking' | 'running';
  glb: Uint8Array;
  fbx: Uint8Array | null;
}

export interface MeshyRigResult {
  sourceJobId: string;
  // Skeleton type (e.g. style_01). Often absent on the rig response (PLAN §2.4);
  // resolved via listActions in P2 when needed.
  rigType: string | null;
  // Epoch ms when the rig task + its signed URLs expire (~3 days).
  expiresAt: number | null;
  glb: Uint8Array;
  fbx: Uint8Array | null;
  basicAnimations: MeshyBasicAnimation[];
}

export interface MeshyAnimateResult {
  sourceJobId: string;
  expiresAt: number | null;
  glb: Uint8Array;
  fbx: Uint8Array | null;
}

// One entry in the Meshy motion catalog (PER-DOCS shape; tolerant parse).
export interface MeshyAction {
  id: number;
  name: string;
  category: string | null;
  rigType: string | null;
  isFree: boolean;
  previewGifUrl: string | null;
}

// Injectable transports so smokes can run without a real network call.
export type FetchLike = (url: string, init: RequestInit) => Promise<Response>;
export type DownloadLike = (url: string) => Promise<Uint8Array>;

export interface MeshyProviderDeps {
  env: MeshyEnv;
  // Active game slug for the per-game audit trail (ADR-0002). Smokes may pass any.
  slug: string;
  fetchImpl?: FetchLike;
  downloadImpl?: DownloadLike;
  rateGuard?: RateGuard;
  sleep?: (ms: number) => Promise<void>;
}

// Map a Meshy model_urls key to a durable manifest file role+format.
const MODEL_URL_TO_FILE: Record<string, { role: FileRole; format: FileFormat }> = {
  glb: { role: 'source_mesh', format: 'glb' },
  fbx: { role: 'source_mesh', format: 'fbx' },
  obj: { role: 'source_mesh', format: 'obj' },
  usdz: { role: 'source_mesh', format: 'usdz' },
  stl: { role: 'source_mesh', format: 'stl' },
};

export class MeshyProvider {
  private readonly env: MeshyEnv;
  private readonly slug: string;
  private readonly fetchImpl: FetchLike;
  private readonly downloadImpl: DownloadLike;
  private readonly rateGuard: RateGuard;
  private readonly sleep: (ms: number) => Promise<void>;

  constructor(deps: MeshyProviderDeps) {
    this.env = deps.env;
    this.slug = deps.slug;
    this.fetchImpl = deps.fetchImpl ?? ((url, init) => fetch(url, init));
    this.downloadImpl =
      deps.downloadImpl ?? (async (url) => new Uint8Array(await (await fetch(url)).arrayBuffer()));
    this.rateGuard = deps.rateGuard ?? new RateGuard(this.env.rateLimitPerMin);
    this.sleep = deps.sleep ?? ((ms) => new Promise((r) => setTimeout(r, ms)));
  }

  async generate(input: MeshyGenerateInput): Promise<ProviderResult> {
    const submitPath = pathForMode(input.mode);
    const payload = this.buildPayload(input);

    // Guard BEFORE the quotaed submit.
    this.rateGuard.check();

    const submitResp = await this.post(submitPath, payload);
    // v2 text/refine return `result`; v1 image/multi return `id`.
    const sourceJobId = (submitResp.result as string) ?? (submitResp.id as string) ?? null;
    if (!sourceJobId) {
      throw Object.assign(new Error('meshy submit returned no task id'), { code: 'provider_no_task' });
    }
    await audit(this.slug, { ts: new Date().toISOString(), provider: 'meshy', mode: input.mode, event: 'submit', sourceJobId });

    const urls = await this.poll(input.mode, sourceJobId);

    const files: ProviderResultFile[] = [];
    const seenRoles = new Set<string>();
    for (const [key, mapping] of Object.entries(MODEL_URL_TO_FILE)) {
      const url = urls[key];
      if (!url) continue;
      const roleKey = `${mapping.role}:${mapping.format}`;
      if (seenRoles.has(roleKey)) continue;
      seenRoles.add(roleKey);
      files.push({ role: mapping.role, format: mapping.format, data: await this.downloadImpl(url) });
    }
    if (urls.__thumbnail) {
      files.push({ role: 'preview_image', format: 'png', data: await this.downloadImpl(urls.__thumbnail) });
    }
    if (urls.__texture_base_color) {
      files.push({ role: 'texture', format: 'png', data: await this.downloadImpl(urls.__texture_base_color) });
    }

    return {
      provider: 'meshy',
      mode: input.mode as GenerationMode,
      providerMode: 'real',
      sourceJobId,
      prompt: input.prompt ?? null,
      files,
    };
  }

  // Auto-rig (async submit→poll). Input is either a Meshy mesh task id (fast
  // path) or a public model URL (COS transfer, preferred). Returns the rigged
  // GLB (canonical, self-contained) + FBX, the rig task id (needed as the
  // /animations input), its rigType + expiry, and any free bundled walk/run.
  async rig(input: MeshyRigInput): Promise<MeshyRigResult> {
    if (!input.inputTaskId && !input.modelUrl) {
      throw Object.assign(new Error('meshy rig needs inputTaskId or modelUrl'), {
        code: 'invalid_rig_input',
      });
    }
    const payload: Record<string, unknown> = {};
    if (input.inputTaskId) payload.input_task_id = input.inputTaskId;
    if (input.modelUrl) payload.model_url = input.modelUrl;
    if (input.heightMeters !== undefined) payload.height_meters = input.heightMeters;

    this.rateGuard.check();
    const submit = await this.post(PATH_RIGGING, payload);
    const taskId = submitTaskId(submit);
    if (!taskId) {
      throw Object.assign(new Error('meshy rig submit returned no task id'), { code: 'provider_no_task' });
    }
    await audit(this.slug, { ts: new Date().toISOString(), provider: 'meshy', mode: 'image', event: 'submit', sourceJobId: taskId, detail: 'rig' });

    const resp = await this.pollTask(PATH_RIGGING, taskId, 'rig');
    const result = asRecord(resp.result);
    const glbUrl = str(result.rigged_character_glb_url);
    if (!glbUrl) {
      throw Object.assign(new Error('meshy rig returned no rigged glb'), { code: 'provider_no_output' });
    }
    const fbxUrl = str(result.rigged_character_fbx_url);
    return {
      sourceJobId: taskId,
      rigType: str(result.rig_type),
      expiresAt: numOrNull(resp.expires_at),
      glb: await this.downloadImpl(glbUrl),
      fbx: fbxUrl ? await this.downloadImpl(fbxUrl) : null,
      basicAnimations: await this.extractBasicAnimations(result),
    };
  }

  // Apply one motion (async submit→poll). MUST be driven by Meshy's own
  // rig_task_id; an external FBX is not accepted (ADR-0006 §Decision 3).
  async animate(input: MeshyAnimateInput): Promise<MeshyAnimateResult> {
    this.rateGuard.check();
    const submit = await this.post(PATH_ANIMATION, {
      rig_task_id: input.rigTaskId,
      action_id: input.actionId,
    });
    const taskId = submitTaskId(submit);
    if (!taskId) {
      throw Object.assign(new Error('meshy animate submit returned no task id'), { code: 'provider_no_task' });
    }
    await audit(this.slug, { ts: new Date().toISOString(), provider: 'meshy', mode: 'image', event: 'submit', sourceJobId: taskId, detail: `animate:${input.actionId}` });

    const resp = await this.pollTask(PATH_ANIMATION, taskId, 'animate');
    const result = asRecord(resp.result);
    const glbUrl = str(result.animation_glb_url);
    if (!glbUrl) {
      throw Object.assign(new Error('meshy animate returned no animation glb'), { code: 'provider_no_output' });
    }
    const fbxUrl = str(result.animation_fbx_url);
    return {
      sourceJobId: taskId,
      expiresAt: numOrNull(resp.expires_at),
      glb: await this.downloadImpl(glbUrl),
      fbx: fbxUrl ? await this.downloadImpl(fbxUrl) : null,
    };
  }

  // Motion catalog — the full public action set (~680). Meshy exposes NO HTTP
  // endpoint to list actions (verified 2026-06-21 against the official API
  // reference: only POST/GET/DELETE /openapi/v1/animations exist). The catalog
  // is a static table scraped from the web animation-library page and vendored
  // at shared/meshy-actions.ts. There is no per-rig "compatible actions"
  // endpoint either, so rigType filtering is done by the caller. Zero credits.
  async listActions(): Promise<MeshyAction[]> {
    return MESHY_ACTIONS.map((row) => {
      const [id, name, category, , previewGifRel] = row;
      return {
        id,
        name,
        category,
        rigType: null,
        isFree: false,
        previewGifUrl: previewGifRel ? `${MESHY_ACTION_BASE}${previewGifRel}` : null,
      };
    });
  }

  // Remaining credit balance, for an optional pre-flight before a paid call.
  async getBalance(): Promise<number> {
    const resp = await this.get(PATH_BALANCE);
    const raw = resp.balance ?? resp.credits ?? asRecord(resp.data).balance;
    const n = typeof raw === 'number' ? raw : Number(raw);
    return Number.isFinite(n) ? n : 0;
  }

  // Download walk/run from a rig result's basic_animations block (free, bundled).
  private async extractBasicAnimations(result: Record<string, unknown>): Promise<MeshyBasicAnimation[]> {
    const block = asRecord(result.basic_animations);
    const out: MeshyBasicAnimation[] = [];
    for (const category of ['walking', 'running'] as const) {
      const glbUrl = str(block[`${category}_glb_url`]);
      if (!glbUrl) continue;
      const fbxUrl = str(block[`${category}_fbx_url`]);
      out.push({
        category,
        glb: await this.downloadImpl(glbUrl),
        fbx: fbxUrl ? await this.downloadImpl(fbxUrl) : null,
      });
    }
    return out;
  }

  // Poll a task by id until terminal (status is UPPER-CASE). Returns the full
  // success response so rig/animate can read their own result fields.
  private async pollTask(path: string, taskId: string, label: string): Promise<Record<string, unknown>> {
    const deadline = Date.now() + this.env.pollTimeoutMs;
    while (Date.now() < deadline) {
      const resp = await this.get(`${path}/${taskId}`);
      const status = String(resp.status ?? '').toUpperCase();
      if (status === SUCCESS) {
        await audit(this.slug, { ts: new Date().toISOString(), provider: 'meshy', mode: 'image', event: 'poll_succeeded', sourceJobId: taskId, detail: label });
        return resp;
      }
      if (FAILURE.has(status)) {
        await audit(this.slug, { ts: new Date().toISOString(), provider: 'meshy', mode: 'image', event: 'poll_failed', sourceJobId: taskId, detail: `${label}:${taskErrorMessage(resp) ?? status}` });
        throw Object.assign(new Error(`meshy ${label} ${status}: ${taskErrorMessage(resp) ?? ''}`), { code: 'provider_failed' });
      }
      await this.sleep(this.env.pollIntervalMs);
    }
    await audit(this.slug, { ts: new Date().toISOString(), provider: 'meshy', mode: 'image', event: 'poll_timeout', sourceJobId: taskId, detail: label });
    throw Object.assign(new Error(`meshy ${label} poll timed out`), { code: 'provider_timeout' });
  }

  private buildPayload(input: MeshyGenerateInput): Record<string, unknown> {
    const polycount =
      input.targetPolycount !== undefined ? clampTargetPolycount(input.targetPolycount) : undefined;

    if (input.mode === 'text') {
      const payload: Record<string, unknown> = { mode: 'preview', prompt: input.prompt ?? '' };
      if (input.aiModel) payload.ai_model = input.aiModel;
      if (polycount) {
        payload.should_remesh = true;
        payload.target_polycount = polycount;
      }
      this.applyProviderParams(payload, input.params);
      return payload;
    }
    if (input.mode === 'refine') {
      const payload: Record<string, unknown> = { mode: 'refine', preview_task_id: input.previewTaskId };
      if (input.texturePrompt) payload.texture_prompt = input.texturePrompt;
      if (typeof input.enablePbr === 'boolean') payload.enable_pbr = input.enablePbr;
      return payload;
    }
    if (input.mode === 'image') {
      const payload: Record<string, unknown> = { image_url: input.imageUrl ?? '' };
      this.applyMeshOptions(payload, input, polycount);
      this.applyProviderParams(payload, input.params);
      return payload;
    }
    // views
    const payload: Record<string, unknown> = { image_urls: (input.imageUrls ?? []).slice(0, 4) };
    this.applyMeshOptions(payload, input, polycount);
    this.applyProviderParams(payload, input.params);
    return payload;
  }

  private applyProviderParams(
    payload: Record<string, unknown>,
    params: Record<string, string | number | boolean> | undefined,
  ): void {
    if (!params) return;
    Object.assign(payload, params);
    if (payload.topology !== undefined && payload.should_remesh === undefined) {
      payload.should_remesh = true;
    }
  }

  private applyMeshOptions(
    payload: Record<string, unknown>,
    input: MeshyGenerateInput,
    polycount: number | undefined,
  ): void {
    if (input.aiModel) payload.ai_model = input.aiModel;
    if (typeof input.enablePbr === 'boolean') payload.enable_pbr = input.enablePbr;
    if (typeof input.shouldTexture === 'boolean') payload.should_texture = input.shouldTexture;
    if (polycount) payload.target_polycount = polycount;
  }

  private async poll(mode: MeshyMode, taskId: string): Promise<Record<string, string>> {
    const deadline = Date.now() + this.env.pollTimeoutMs;
    while (Date.now() < deadline) {
      const resp = await this.get(`${pathForMode(mode)}/${taskId}`);
      const status = String(resp.status ?? '').toUpperCase();
      if (status === SUCCESS) {
        await audit(this.slug, { ts: new Date().toISOString(), provider: 'meshy', mode, event: 'poll_succeeded', sourceJobId: taskId, detail: status });
        return extractUrls(resp);
      }
      if (FAILURE.has(status)) {
        await audit(this.slug, { ts: new Date().toISOString(), provider: 'meshy', mode, event: 'poll_failed', sourceJobId: taskId, detail: taskErrorMessage(resp) ?? status });
        throw Object.assign(new Error(`meshy task ${status}: ${taskErrorMessage(resp) ?? ''}`), { code: 'provider_failed' });
      }
      await this.sleep(this.env.pollIntervalMs);
    }
    await audit(this.slug, { ts: new Date().toISOString(), provider: 'meshy', mode, event: 'poll_timeout', sourceJobId: taskId });
    throw Object.assign(new Error('meshy poll timed out'), { code: 'provider_timeout' });
  }

  private async post(path: string, body: unknown): Promise<Record<string, unknown>> {
    const resp = await this.fetchImpl(`${this.env.baseUrl}${path}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${this.env.apiKey}` },
      body: JSON.stringify(body),
    });
    if (!resp.ok) throw httpError(resp.status);
    return (await resp.json()) as Record<string, unknown>;
  }

  private async get(path: string): Promise<Record<string, unknown>> {
    const resp = await this.fetchImpl(`${this.env.baseUrl}${path}`, {
      method: 'GET',
      headers: { Authorization: `Bearer ${this.env.apiKey}` },
    });
    if (!resp.ok) throw httpError(resp.status);
    return (await resp.json()) as Record<string, unknown>;
  }
}

// Map a non-2xx Meshy status to a stable error code (ADR-0006 / PLAN §6). 402 =
// insufficient credits, 404 = capability not enabled, 429 = rate limited; the
// `status` is attached so the handler/UI can surface the exact HTTP code.
function httpError(status: number): Error & { code: string; status: number } {
  const code =
    status === 400 ? 'provider_bad_request'
    : status === 401 ? 'provider_unauthorized'
    : status === 402 ? 'provider_insufficient_credits'
    : status === 404 ? 'provider_not_enabled'
    : status === 429 ? 'provider_rate_limited'
    : 'provider_http_error';
  return Object.assign(new Error(`meshy http ${status}`), { code, status });
}

// v2 text/refine + rig/animate return the task id in `result`; v1 image/multi in `id`.
function submitTaskId(resp: Record<string, unknown>): string | null {
  return (resp.result as string) ?? (resp.id as string) ?? null;
}

function asRecord(value: unknown): Record<string, unknown> {
  return value && typeof value === 'object' ? (value as Record<string, unknown>) : {};
}

function str(value: unknown): string | null {
  return typeof value === 'string' && value ? value : null;
}

function numOrNull(value: unknown): number | null {
  return typeof value === 'number' && Number.isFinite(value) ? value : null;
}

function pathForMode(mode: MeshyMode): string {
  if (mode === 'text' || mode === 'refine') return PATH_TEXT;
  if (mode === 'image') return PATH_IMAGE;
  if (mode === 'views') return PATH_MULTI;
  throw Object.assign(new Error(`meshy unsupported mode: ${mode}`), { code: 'invalid_mode' });
}

function taskErrorMessage(resp: Record<string, unknown>): string | undefined {
  const err = resp.task_error as Record<string, unknown> | undefined;
  return err && typeof err.message === 'string' && err.message ? err.message : undefined;
}

// Flatten the Meshy success response into a single url map. model_urls keys map
// to mesh files; thumbnail_url + texture_urls[0].base_color are namespaced with
// a `__` prefix so they never collide with model format keys.
function extractUrls(resp: Record<string, unknown>): Record<string, string> {
  const out: Record<string, string> = {};
  const mu = resp.model_urls;
  if (mu && typeof mu === 'object') {
    for (const [key, value] of Object.entries(mu as Record<string, unknown>)) {
      if (typeof value === 'string' && value) out[key] = value;
    }
  }
  if (typeof resp.thumbnail_url === 'string' && resp.thumbnail_url) {
    out.__thumbnail = resp.thumbnail_url;
  }
  const tu = resp.texture_urls;
  if (Array.isArray(tu) && tu[0] && typeof tu[0] === 'object') {
    const bc = (tu[0] as Record<string, unknown>).base_color;
    if (typeof bc === 'string' && bc) out.__texture_base_color = bc;
  }
  return out;
}
